apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-frontend-svc
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: todo-frontend