apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=postgresql user=postgres password=password dbname=dapr_state port=5432 sslmode=disable"
  - name: actorStateStore
    value: "true"
  - name: concurrency
    value: "first-write"
  - name: tableName
    value: "dapr_state_store"
  - name: connectionMaxIdleTime
    value: "0"
  - name: connectionMaxLifetime
    value: "0"
  - name: migrationDirection
    value: "up"
  - name: secretStore
    value: "kubernetes"