apiVersion: v2
name: todo-chatbot
description: A Helm chart for deploying the Todo Chatbot application on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/AlishbaAslam/Hackathon-II
sources:
  - https://github.com/AlishbaAslam/Hackathon-II
keywords:
  - todo
  - chatbot
  - kubernetes
  - minikube
  - fastapi
  - nextjs
maintainers:
  - name: Hackathon Team
    email: team@example.com
annotations:
  category: Infrastructure